version: "3.9"
services:
  db:
    image: postgres:12.15
    restart: always
    environment:
      POSTGRES_DB: languages
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres123
    ports:
      - 5432:5432
    networks:
      - network-languagem
  api:
    image: rafaelcarmonagil/app-desafio-postech:1.0
    environment:
      JAVA_OPTS: -Ddatabase_url=db -Ddatabase_user=postgres -Ddatabase_password=postgres123
    ports:
      - 8080:8080
    networks:
      - network-languagem
    depends_on:
      - db
networks:
  network-languagem:
    driver: bridge